###
GET http://localhost:8080/api/v1/category/admin

###
POST http://localhost:8080/api/v1/category
Content-Type: application/json

{
  "orderNumber": 1,
  "nameUz": "Texnika",
  "nameRu": "Texnika Ru",
  "nameEn": "Technology",
  "categoryKey": "tech"
}

###
DELETE http://localhost:8080/api/v1/category/1

###
GET http://localhost:8080/api/v1/category/lang/uz