###
GET http://localhost:8080/api/v1/region/admin

###
POST http://localhost:8080/api/v1/region
Content-Type: application/json

{
  "orderNumber": 4,
  "nameUz": "Namangan",
  "nameRu": "Namangan Ru",
  "nameEn": "Namangan En",
  "regionKey": "nam"
}

###
DELETE http://localhost:8080/api/v1/region/1

###
GET http://localhost:8080/api/v1/region/lang
Accept-Language: EN