###
POST http://localhost:8080/api/v1/section
Content-Type: application/json

{
  "orderNumber": 2,
  "nameUz": "Bolalar",
  "nameRu": "Kids Ru",
  "nameEn": "Kids En",
  "sectionKey": "kids"
}

###
DELETE http://localhost:8080/api/v1/section/1

###
GET http://localhost:8080/api/v1/section/lang/uz

###
GET http://localhost:8080/api/v1/section/admin?
    page=1&
    size=1